### ISSUE TITLE
Propose having an xts array as an output option for RWDataPlot.

### ISSUE THREAD

**Issue by tjrocha** [rabutler/RWDataPlot#13]
Hey Alan! I've found that working with the xts package works really well for rdf outputs. I've implemented it in [this project](https://jrocha.shinyapps.io/rdfModelOutputDashboard/) and it works ok. Having it as an xts object also makes it work out of the box for a lot of graphing and analysis packages.

``
- library(xts)
- library(zoo)
- library(RWDataPlot)
- rawRDF <- read.rdf(rdfFileName)
- tArray <- rawRDF$runs[[1]]$times
-  # OPERATIONS IN ORDER OF EXECUTION
-  # 1. rdfSlotToMatrix - read data for 'ithSlotName' string given 'rdf' file
-  # 2. cbind - combine datetime and data series arrays
-  # 3. data.frame - define R dataframe for conversion to XTS
-  # 4. read.zoo - convert dataframe to zoo matrix
-  # 5. as.xts - convert zoo matrix to XTS
-  # 6. Storage.mode() - convert char values in the XTS matrix to numeric
- rdf <- as.xts(read.zoo(data.frame(cbind(tArray,rdfSlotToMatrix(rawRDF, "Mead.Inflow")))))
- storage.mode(rdf) <- "numeric"

``

As an xts object, we can easily perform lots of other functions relatively easier such as getting percentile levels for the entire array via a custom function

``
-  # DEFINE PERCENTILE VALUES OF INTEREST
-  toPctls <- function(rdfRawData) quantile(rdfRawData, c(.10,.25,.50,.75,.90))
-  # GET PERCENTILE VALUES OF ENTIRE ARRAY BY EOCY
-  eocyPctlXts <- apply.yearly(rdfRawData()[endpoints(rdfRawData(), on="years", k=1)],toPctls)
-  # GET PERCENTILE VALUES OF ENTIRE ARRAY BY MONTH
-  montPctlXts <- apply.monthly(rdfRawData(),toPctls)

``

or get an annual sum via the built in mean function

``
-  # GET CY ANNUAL SUMS BY TRACE 
-  annlSumsXts <- apply.yearly(rdfRawData(),mean)*12

``

plotting is relatively easy also via a sample graphing library such as DyGraphs

``
-  library(dygraphs)
-  plotTsRawData <- dygraph(rdf)

``

Just wanted to get your opinion on it. I will commit it to my local branch and do a pull request if you think its worthwhile.

**Comment by rabutler** [comment]
Hey @tjrocha! This seems like a great idea! Looks like it has the potential to simplify a lot of the code and make it much easier to deal with computations, so I'm all for it. So I'm clear, are you proposing adding a new function, similar to rdfSlotToMatrix? My only concern/preference is that we do it in such a way that any old scripts will still correctly run without having to be modified.

Also, I like the results viewer! Looks great!

**Comment by tjrocha** [comment]
Yes, the additions I'm proposing should not impact any of the existing code and functions. I was thinking of adding an rdfSlotToXTS() function in rdf_helperFunctions.R similar to rdfSlotToMatrix(). Then I was thinking of either (1) adding another code file with functions to perform the XTS stats and aggregation (stats_helperFunctions.R?) or (2) building these same functions and placing them in the appropriate *.R files that already exist. Your thoughts?

**Comment by rabutler** [comment]
Perfect! Hmm, I could see putting them in aggregations.R, but it also might be nice to have the functions that work with xts objects isolated in their own file. I'm leaning towards a new file, but if it makes more sense to you to add to aggregations.R I'm good with that too. Thanks @tjrocha!

**Comment by tjrocha** [comment]
New file it is then. Thanks @rabutler!

**Comment by tjrocha** [comment]
Made the changes and additions below to my fork. Testing worked fine but I'll sleep on it and test again before doing a pull request. Brief summary of changes and additions follow:

1. Added rdfSlotToXTS() in rdf_helperFunctions.R
2. Added new file; xts_heperFunctions.R with functions that do the following:
- Get percentile values at desired percentile levels for the entire array [getArrayPercentilesByMonth]
- Get EOCY percentile values at desired percentile levels for the entire array [getArrayPercentilesByEOCY]
- Get the values for a particular month for each trace [getTraceValuesByMonth]
- Calculate the CY average for each trace [getTraceAnnualAvgByCY]
- Calculate the CY sum for each trace [getTraceAnnualSumsByCY]
- Get percentile values at desired percentile levels by CY sums for the entire array [getArrayPercentilesByAnnualSumsByEOCY]
- Calculate percent of traces that meet a threshold for the entire array [getArrayThresholdExceedance]

**Comment by tjrocha** [comment]
Failed to mention that all outputs are time-series so there is a value for each month or year depending on the function called.

**Comment by rabutler** [comment]
Thanks @tjrocha. A couple of thoughts. Is getArrayPercentilesByAnnualSumsByEOCY common enough that it needs its own function, or can we combine getTraceAnnualSumsByCY with getArrayPercentilesByEOCY? If the array we are operating on is always the first argument to these functions, then we should be able to take advantage of the pipe operator from the magrittr package, which could enhance the code readability. For example:
`mySlot <- rdfSlotToXTS(rdf) %>% getTraceAnnualSumsByCY() %>% getArrayPercentilesByEOCY(c(.1,.5,.9))`

Can we shorten some of these names, if possible? For example getTraceAnnualAvgByCY seems a little redundant. Maybe getTraceCYAvg. 

Next, before you submit the pull request, will you make sure all of the functions are documented with ROxygen style comments and parameters, so we'll have documentation for these new functions? http://r-pkgs.had.co.nz/man.html is a helpful guide for this.

Finally, we'll want to add all of the functions that should be available to the user to the NAMESPACE file. I'm guessing its all 9 of the functions you mention above.

**Comment by tjrocha** [comment]
Yeah, I'll probably go through the functions again and do some optimization, clean-up, and another round of testing. The _juices_ were flowing so I just wanted to get everything in there before I forgot. I'll be sure to get the documentation in place before I do a pull request. Thanks for the feedback!

**Comment by rabutler** [comment]
Sounds great. thanks @tjrocha!

**Comment by rabutler** [comment]
closed by #16 and available in v0.4.1
